/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author pro
 */
public class GUIFive extends java.awt.Frame {

    /**
     * Creates new form GUIFive
     */
    public GUIFive() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        button1 = new java.awt.Button();
        l1 = new java.awt.Label();
        t1 = new java.awt.TextField();
        button2 = new java.awt.Button();
        panel1 = new java.awt.Panel();
        button3 = new java.awt.Button();
        button4 = new java.awt.Button();

        button1.setLabel("button1");

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });
        setLayout(null);

        l1.setBackground(new java.awt.Color(204, 255, 204));
        l1.setText("Name");
        add(l1);
        l1.setBounds(70, 70, 80, 40);
        add(t1);
        t1.setBounds(170, 60, 120, 50);

        button2.setLabel("Save");
        add(button2);
        button2.setBounds(310, 60, 100, 50);

        panel1.setLayout(null);

        button3.setLabel("Cancel");
        panel1.add(button3);
        button3.setBounds(30, 10, 55, 24);
        button3.getAccessibleContext().setAccessibleName("Cancel");

        button4.setLabel("Exit");
        panel1.add(button4);
        button4.setBounds(280, 10, 60, 24);
        button4.getAccessibleContext().setAccessibleName("Exit");

        add(panel1);
        panel1.setBounds(50, 190, 360, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIFive().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button1;
    private java.awt.Button button2;
    private java.awt.Button button3;
    private java.awt.Button button4;
    private java.awt.Label l1;
    private java.awt.Panel panel1;
    private java.awt.TextField t1;
    // End of variables declaration//GEN-END:variables
}
